# -*- coding: utf-8 -*-
"""comparativo bancos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sKCdB7IuI4N7vexefPJLIwFuEqcjnLX
"""

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# === 1. Cargar archivo ===
archivo = "archivo_bancos.xlsx"  # Cambia por tu nombre de archivo
bancos = pd.read_excel(archivo, sheet_name="Bancos")
mayor = pd.read_excel(archivo, sheet_name="Mayor")

# === 2. Normalizar columnas ===
bancos["Valor"] = bancos["Valor"].round(2)
mayor["Debe"] = mayor["Debe"].fillna(0).round(2)
mayor["Haber"] = mayor["Haber"].fillna(0).round(2)

# === 3. Crear columna esperada según tipo ===
def obtener_valor_esperado(row):
    if row["Tipo"] == "C":
        return row["Valor"], 0  # Debe
    elif row["Tipo"] == "D":
        return 0, row["Valor"]  # Haber
    else:
        return 0, 0

bancos[["Debe_esperado", "Haber_esperado"]] = bancos.apply(
    lambda row: pd.Series(obtener_valor_esperado(row)), axis=1
)

# === 4. Conciliación ===
resumen = []

for index, row in bancos.iterrows():
    encontrado = mayor[
        (mayor["Debe"] == row["Debe_esperado"]) &
        (mayor["Haber"] == row["Haber_esperado"])
    ]

    if encontrado.empty:
        estado = "NO COINCIDE"
    else:
        estado = "OK"

    resumen.append({
        "Fecha": row["Fecha"],
        "Descripción": row["Descripción"],
        "Tipo": row["Tipo"],
        "Valor": row["Valor"],
        "Debe esperado": row["Debe_esperado"],
        "Haber esperado": row["Haber_esperado"],
        "Estado": estado
    })

df_resumen = pd.DataFrame(resumen)

# === 5. Guardar nuevo archivo ===
archivo_salida = "conciliacion_resultado.xlsx"
df_resumen.to_excel(archivo_salida, sheet_name="Resumen", index=False)

# === 6. Resaltar en amarillo los que no coinciden ===
wb = load_workbook(archivo_salida)
ws = wb["Resumen"]

amarillo = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")

for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
    if row[6].value == "NO COINCIDE":  # Columna Estado
        for cell in row:
            cell.fill = amarillo

wb.save(archivo_salida)

print("Conciliación terminada. Archivo generado:", archivo_salida)